### ISSUE TITLE
Changes to "How to use" wiki page

### ISSUE THREAD

**Issue by angelwire** [blender-to-gmstudio/blender-to-smf#25]
Just a couple quick suggestions for the how to use wiki page.
- I think it would be useful to mention SMF's bone scaling limitation in the wiki.
- The armature modifier in Blender can be changed to better reflect SMF's dual quaternion approach by checking the "Preserve Volume" option in the armature modifier: [https://files.slack.com/files-pri/T0QDQGJQG-F02MS5XQW6R/image.png](url)

**Comment by bartteunis** [comment]
Added some information on the "Preserve Volume" option here: https://github.com/blender-to-gmstudio/blender-to-smf/wiki/How-To-Use#armature-modifier-settings

**Comment by bartteunis** [comment]
For the first suggestion: do you mean the limitation on armatures where there is a difference in scale (#22)? The fact that SMF uses dual quaternions and so cannot store a scale factor? Or something else?

**Comment by angelwire** [comment]
I was referring to the fact that SMF uses dual quaternions so it doesn't store the scale factor. I didn't tell my animator about the bone scaling limitations, so when he scaled the bones in blender and wasn't seeing results in the game he thought it was a glitch.

**Comment by bartteunis** [comment]
Also added a paragraph on bone scaling limitations now over here: https://github.com/blender-to-gmstudio/blender-to-smf/wiki/How-To-Use#bone-scale.
